In [6]:
pip install supervision --user

  Using cached supervision-0.16.0-py3-none-any.whl.metadata (14 kB)
  Using cached opencv_python_headless-4.8.1.78-cp37-abi3-win_amd64.whl.metadata (20 kB)
Using cached supervision-0.16.0-py3-none-any.whl (72 kB)
Using cached opencv_python_headless-4.8.1.78-cp37-abi3-win_amd64.whl (38.0 MB)
Note: you may need to restart the kernel to use updated packages.


In [1]:
import cv2
import torch
import yaml
from pathlib import Path
import ultralytics
from ultralytics import YOLO
import supervision as sv

In [2]:
# Load YOLOv8 model
model_path = "C:/Users/IP-03/Documents/Benji/runs/detect/2023-11-24-50epchs-nopre/weights/best.pt" #change the model pt here
model = YOLO(model_path)

# Load YAML
args_path = "C:/Users/IP-03/Documents/Benji/runs/detect/2023-11-24-50epchs-nopre/args.yaml" #change the args here
with open(args_path, 'r') as f:
    config = yaml.safe_load(f)

In [3]:
metrics = model.val()  # no arguments needed, dataset and settings remembered
metrics.box.map    # map50-95
metrics.box.map50  # map50
metrics.box.map75  # map75
metrics.box.maps

Ultralytics YOLOv8.0.210  Python-3.11.3 torch-2.0.1+cu118 CUDA:0 (NVIDIA GeForce GTX 1080 Ti, 11264MiB)
YOLOv8n summary (fused): 168 layers, 3008378 parameters, 0 gradients, 8.1 GFLOPs
val: Scanning D:\Benji\dataset\labels\val.cache... 32153 images, 0 backgrounds, 0 corrupt: 100%|██████████| 32153/32153
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 2010/2010 [0
                   all      32153      32153      0.489      0.587      0.518      0.454
      short sleeve top      32153       9495      0.549      0.959      0.815      0.751
       long sleeve top      32153       4262      0.604      0.284      0.473      0.402
  short sleeve outwear      32153        105      0.386      0.286      0.278      0.249
   long sleeve outwear      32153       1663      0.374      0.924      0.568      0.515
                  vest      32153       1736      0.675      0.793      0.765       0.65
                 sling      32153        

array([    0.45382,     0.75063,     0.40216,     0.24875,     0.51538,     0.64966,     0.41716,     0.47791,     0.43259,      0.2201,     0.46435,     0.27193,     0.70598,     0.34312])

In [30]:
print(metrics.box.p)
print(metrics.box.r)

[    0.54901      0.6044     0.38638     0.37391     0.67474     0.64452     0.25837     0.31308     0.23883     0.83278     0.51175     0.62726       0.345]
[    0.95914     0.28427     0.28571     0.92423      0.7932     0.42222     0.92045     0.91066     0.65303    0.051035    0.024982     0.80208     0.59695]


In [32]:
#Calculate micro metrics
total_tp = np.sum(metrics.box.p * metrics.box.r)
total_fp = np.sum(metrics.box.p) - total_tp
total_fn = np.sum(metrics.box.r) - total_tp

micro_precision = total_tp / (total_tp + total_fp)
micro_recall = total_tp / (total_tp + total_fn)
micro_f1 = 2 * (micro_precision * micro_recall) / (micro_precision + micro_recall)

#Calculate macro metrics
macro_precision = np.mean(metrics.box.p)
macro_recall = np.mean(metrics.box.r)
macro_f1 = 2 * (macro_precision * macro_recall) / (macro_precision + macro_recall)

# Print the results
print("Micro Precision:", micro_precision)
print("Micro Recall:", micro_recall)
print("Micro F1 Score:", micro_f1)

print("Macro Precision:", macro_precision)
print("Macro Recall:", macro_recall)
print("Macro F1 Score:", macro_f1)

Micro Precision: 0.5353651682323187
Micro Recall: 0.4463756767458433
Micro F1 Score: 0.486837214725785
Macro Precision: 0.489233582622308
Macro Recall: 0.5867672297355547
Macro F1 Score: 0.5335799576950842
